### ISSUE TITLE
How to convert JSON data to numpy to train with openrec?

### ISSUE THREAD

**Issue by baophamtd** [ylongqi/openrec#37]
Hi there. I'm trying to convert my JSON dataset that I've got from Yelp to numpy array in order to train a recommender with openrec, and I don't know how to do it correctly.

I have printed out the numpy data from dataset folder to see if I can mimic the structure, but I didn't quite get it. Can someone please give me a quick tutorial on how to set up my data to train?

For example, I have a small set of data like this:

```
[
    {
        "funny": 0, 
        "user_id": "msQe1u7Z_XuqjGoqhB0J5g", 
        "review_id": "x7mDIiDB3jEiPGPHOmDzyw", 
        "text": "The pizza was okay. Not the best I've had. I prefer Biaggio's on Flamingo / Fort Apache. The chef there can make a MUCH better NY style pizza. The pizzeria @ Cosmo was over priced for the quality and lack of personality in the food. Biaggio's is a much better pick if youre going for italian - family owned, home made recipes, people that actually CARE if you like their food. You dont get that at a pizzeria in a casino. I dont care what you say...", 
        "business_id": "iCQpiavjjPzJ5_3gPD5Ebg", 
        "stars": 2, 
        "date": "2011-02-25", 
        "useful": 0, 
        "cool": 0
    }, 
    {
        "funny": 0, 
        "user_id": "msQe1u7Z_XuqjGoqhB0J5g", 
        "review_id": "dDl8zu1vWPdKGihJrwQbpw", 
        "text": "I love this place! My fiance And I go here atleast once a week. The portions are huge! Food is amazing. I love their carne asada. They have great lunch specials... Leticia is super nice and cares about what you think of her restaurant. You have to try their cheese enchiladas too the sauce is different And amazing!!!", 
        "business_id": "pomGBqfbxcqPv14c3XH-ZQ", 
        "stars": 5, 
        "date": "2012-11-13", 
        "useful": 0, 
        "cool": 0
    }, 
    {
        "funny": 1, 
        "user_id": "msQe1u7Z_XuqjGoqhB0J5g", 
        "review_id": "LZp4UX5zK3e-c5ZGSeo3kA", 
        "text": "Terrible. Dry corn bread. Rib tips were all fat and mushy and had no flavor. If you want bbq in this neighborhood go to john mulls roadkill grill. Trust me.", 
        "business_id": "jtQARsP6P-LbkyjbO1qNGg", 
        "stars": 1, 
        "date": "2014-10-23", 
        "useful": 3, 
        "cool": 1
    }, 
    {
        "funny": 0, 
        "user_id": "msQe1u7Z_XuqjGoqhB0J5g", 
        "review_id": "Er4NBWCmCD4nM8_p1GRdow", 
        "text": "Back in 2005-2007 this place was my FAVORITE thai place EVER. I'd go here ALLLLL the time. I never had any complaints. Once they started to get more known and got busy, their service started to suck and their portion sizes got cut in half. I have a huge problem with paying MORE for way less food. The last time I went there I had the Pork Pad se Ew and it tasted good, but I finished my plate and was still hungry. I used to know the manager here and she would greet me with a \"Hello Melissa, nice to see you again, diet coke & pad thai or pad se ew?\" Now a days, I know she still knows me but she disregards my presence. Also, I had asked her what was up with the new portion sizes and she had no answer for me. Great food but not worth the money. I havent been back in over a year because I refuse to pay $10-15 for dinner and still be hungry after. Sorry PinKaow, you are not what you used to be!!", 
        "business_id": "elqbBhBfElMNSrjFqW3now", 
        "stars": 2, 
        "date": "2011-02-25", 
        "useful": 2, 
        "cool": 0
    }, 
    {
        "funny": 0, 
        "user_id": "msQe1u7Z_XuqjGoqhB0J5g", 
        "review_id": "jsDu6QEJHbwP2Blom1PLCA", 
        "text": "Delicious healthy food. The steak is amazing. Fish and pork are awesome too. Service is above and beyond. Not a bad thing to say about this place. Worth every penny!", 
        "business_id": "Ums3gaP2qM3W1XcA5r6SsQ", 
        "stars": 5, 
        "date": "2014-09-05", 
        "useful": 0, 
        "cool": 0
    }, 
    {
        "funny": 0, 
        "user_id": "msQe1u7Z_XuqjGoqhB0J5g", 
        "review_id": "pfavA0hr3nyqO61oupj-lA", 
        "text": "This place sucks. The customer service is horrible. They dont serve food unless you order a pizza from a neighboring restaurant. Who does that? They dont control their crowd. Many times I've gone I've seen fights. The bartenders suck - I've almost got in a fight with one because she was a complete bitch. Refused to serve me a drink because she was \"busy\" celebrating her friends birthday BEHIND THE BAR. This place is ridiculous. I will NEVER go there again.. EVER.", 
        "business_id": "vgfcTvK81oD4r50NMjU2Ag", 
        "stars": 1, 
        "date": "2011-02-25", 
        "useful": 2, 
        "cool": 0
    }, 
    {
        "funny": 0, 
        "user_id": "msQe1u7Z_XuqjGoqhB0J5g", 
        "review_id": "brokEno2n7s4vrwmmUdr9w", 
        "text": "If you like Thai food, you have to try the original thai bbq. Their pad se ew is to DIE for. Their thai egg rolls are delicious. Basil beef will not let you down (its not on the menu anymore, you have to ask for it!) \n\nYes, the building is not as fancy as some other places. Yes, i've batted a fly off my plate more than once. Yes, I do NOT go to the bathroom their because I dont even WANT to know what it looks like... \n\nBUT.. the thai food is the best in town. The service rocks. And you can get a $25 gift cert. on Restaurant.com for $2. Can you beat that? I think NOT.\n\nThis is the only place my husband and I go for anniversarys, date nights, birthdays.. anything!! I recommend it to everyone I know. If you KNOW good thai food, go here.", 
        "business_id": "AxeQEz3-s9_1TyIo-G7UQw", 
        "stars": 5, 
        "date": "2011-10-10", 
        "useful": 1, 
        "cool": 0
    }
]
```

I can link between the ratings and the restaurants' properties, but I don't know how to make them into numpy array :(

**Comment by ylongqi** [comment]
Hi, a sample of convert raw data into numpy array is here:

https://github.com/ylongqi/openrec/blob/master/legacy_tutorials/OpenRec%20Tutorial%20%231.ipynb

You need to first define your recommendation task, i.e., what are the signals that you are trying to predict? Is it ratings? If so, then you probabaly need three fields: "user_id", "restaurant_id", and "rating".

**Comment by baophamtd** [comment]
@ylongqi Thank you for your response. According to the example you linked, let's say if I have more than just rating data (price level, category, ambience, etc.), then each line of my raw data file should be like this:
`(user_id, business_id, rating, business_price_level, business_category)`
Does it look correct?

Also, I'm trying to understand the codes from the legacy tutorials, but at this line:
`train_structured_arr = np.zeros(interactions_count-11102, dtype=[('user_id', np.int32), ('item_id', np.int32)])`
Do you know why that number `11102` is there? and what's that for?

**Comment by ylongqi** [comment]
> @ylongqi Thank you for your response. According to the example you linked, let's say if I have more than just rating data (price level, category, ambience, etc.), then each line of my raw data file should be like this:
> `(user_id, restaurant_id, rating, restaurant_price_level, restaurant_category)`
> Does it look correct? and what if the value of that key is empty for that certain line (i.e. restaurant_category is unknown), should I put null?

Yes. It looks good - the value of restaurant_category depends on what model you use and how your model is going to handle this data. For example, you can use a dummy "0" to represent unknown entries.

> 
> Also, I'm trying to understand the codes from the legacy tutorials, but at this line:
> `train_structured_arr = np.zeros(interactions_count-11102, dtype=[('user_id', np.int32), ('item_id', np.int32)])`
> Do you know why that number `11102` is there? and what's that for?
> 

11102 are the total number of records hold-out for validation and testing. In other words, interactions_count-11102 denotes the number of records used for training.

> And lastly, if I want to rank a set of businesses by the model after training it, can you suggest me how to do so? Sorry for some basic questions. I'm still new to this AI field.

Given a user, you can call the model.serve function to get a ranking of the business:

https://github.com/ylongqi/openrec/blob/master/openrec/recommenders/recommender.py#L377

**Comment by baophamtd** [comment]
@ylongqi Thanks again for the help. So I've tried to put together my model to train based on the example with this data format:
```
msQe1u7Z_XuqjGoqhB0J5g iCQpiavjjPzJ5_3gPD5Ebg 2
msQe1u7Z_XuqjGoqhB0J5g pomGBqfbxcqPv14c3XH-ZQ 5
msQe1u7Z_XuqjGoqhB0J5g jtQARsP6P-LbkyjbO1qNGg 1
msQe1u7Z_XuqjGoqhB0J5g elqbBhBfElMNSrjFqW3now 2
msQe1u7Z_XuqjGoqhB0J5g Ums3gaP2qM3W1XcA5r6SsQ 5
msQe1u7Z_XuqjGoqhB0J5g vgfcTvK81oD4r50NMjU2Ag 1
msQe1u7Z_XuqjGoqhB0J5g AxeQEz3-s9_1TyIo-G7UQw 5
msQe1u7Z_XuqjGoqhB0J5g zdE82PiD6wquvjYLyhOJNA 5
msQe1u7Z_XuqjGoqhB0J5g EAwh1OmG6t6p3nRaZOW_AA 4
msQe1u7Z_XuqjGoqhB0J5g atVh8viqTj-sqDJ35tAYVg 2
```
Each row contains `user_id` , `restaurant_id` and a corresponding `rating`. They are separated by space and here is my code to train it: 

```
import numpy as np
import random
from openrec.legacy.utils import ImplicitDataset
from openrec.legacy.utils.evaluators import AUC
from openrec.legacy.recommenders import BPR
from openrec.legacy import ImplicitModelTrainer
from openrec.legacy.utils.samplers import PairwiseSampler

#prepare val and test with random values from dataset
#each set would hold 2500 records
#for testing purpose, dataset only has 100000 records
val_indexes = random.sample(range(0, 100000), 5000)
test_indexes = []
for i in range(2500):
    test_indexes.append(val_indexes.pop())

val_structured_arr = np.zeros(2500, dtype=[('user_id', np.str), ('item_id', np.str), ('rating', np.int8)])
test_structured_arr = np.zeros(2500, dtype=[('user_id', np.str), ('item_id', np.str), ('rating', np.int8)])
train_structured_arr = np.zeros(95000, dtype=[('user_id', np.str), ('item_id', np.str), ('rating', np.int8)])

with open('./dataset/user_business_rating_tiny.dat', 'r') as fin:
    counter = 0
    counter_val = 0
    counter_test = 0
    counter_train = 0
    for line in fin:
        item_list = line.split()
        if counter in val_indexes:
            val_structured_arr[counter_val] = (item_list[0], item_list[1], item_list[2])
            counter_val += 1
        elif counter in test_indexes:
            test_structured_arr[counter_test] = (item_list[0], item_list[1], item_list[2])
            counter_test += 1
        else:
            train_structured_arr[counter_train] = (item_list[0], item_list[1], item_list[2])
            counter_train += 1
        counter += 1

#below hardcoded numbers are calculated from the dataset
train_dataset = ImplicitDataset(raw_data=train_structured_arr, 
                        max_user=41654, 
                        max_item=31999, name='Train')
val_dataset = ImplicitDataset(raw_data=val_structured_arr, 
                      max_user=41654,
                      max_item=31999, name='Val')
test_dataset = ImplicitDataset(raw_data=test_structured_arr, 
                       max_user=41654,
                       max_item=31999, name='Test')

bpr_model = BPR(batch_size=100, 
                max_user=train_dataset.max_user(), 
                max_item=train_dataset.max_item(), 
                dim_embed=20, 
                opt='Adam')

sampler = PairwiseSampler(batch_size=100, dataset=train_dataset, num_process=1)

auc_evaluator = AUC()

model_trainer = ImplicitModelTrainer(batch_size=1000, 
                             test_batch_size=100, 
                            train_dataset=train_dataset, 
                             model=bpr_model, 
                             sampler=sampler)
model_trainer.train(num_itr=10000, 
                    display_itr=1000, 
                    eval_datasets=[val_dataset, test_dataset],
                    evaluators=[auc_evaluator])
```

I have run the test and got this error:
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/Users/baopham/openrec/venv/lib/python2.7/site-packages/openrec/legacy/utils/samplers/pairwise_sampler.py", line 39, in run
    input_npy[sample_itr] = (entry['user_id'], entry['item_id'], neg_id)
ValueError: invalid literal for long() with base 10: ''
```

Do you know what have been done wrong in this case?

**Comment by baophamtd** [comment]
@ylongqi I've got it to train. Basically, I have to follow exactly like the example. I think it doesn't like the `user_id` or `item_id` to be string, or at least I don't know what data type of numpy to set for string.
Thus, now after I train the model, I have to convert the `user_id` and `item_id` back from index to string.
Thanks a lot for your help, and if you know how to set up the model to train with string `user_id` or `item_id` please let me know.

**Comment by ylongqi** [comment]
Currently the model doesn't expect user_id and item_id to be string. Essentially the logic is that you should handle user and item indexing outside of the model, so that it's much easier to convert them back and forth without relying on the model to do indexing. Below we provided a simple example of indexing, which you may want to refer to:

https://github.com/ylongqi/openrec/blob/master/legacy_tutorials/OpenRec%20Tutorial%20%231.ipynb
